services:

  web:
    build: .  # Search Dockerfile
    #  command: python manage.py runserver 0.0.0.0:8000  # Run server on default Docker IP
    #  "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    # Скрипт, который гарантирует запуск db до запуска web
    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/code/prod/uwsgi/uwsgi.ini"]  # uwsgi --ini /code/prod/uwsgi/uwsgi.ini
    restart: always  #  always restart if container stop
    volumes:
      - .:/code  # Локальные файлы мы помещаем в том code для доступа к нашим файлам
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod  # Переменная среды для запуска prod settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./prod/nginx:/etc/nginx/templates  # Установить и искать файл конфигурации
      - .:/code  # Перебрасываем проект для доступа к статическим файлам
    ports:
      - "80:80"  # http
      - "443:443"  # https

  db:
    image: postgres:14.5  # Версия образа psql
    restart: always  # Перезагружать если сбой
    volumes:
      - .data/db:/var/lib/postgresql/data  # Создаст локальную версию БД в .data/db
    environment:  #  Переменные среды
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:7.0.7
    container_name: redis-1 # Имя контейнера
    restart: always
    volumes:
      - ./data/cache:/data  # Создаст data/cache локально и скопирует их в /data образ
