# fly.toml file generated for educa-project on 2023-01-26T17:47:14+06:00

app = "educa-project"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[processes]
  app = "daphne -b 0.0.0.0 -p 8000 educa.asgi:application"
  worker = "python -m celery -A educa worker --loglevel=info"  # -l info не сработал :)

[env]
  DJANGO_SETTINGS_MODULE = "educa.settings"
  PORT="8000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
