# Generated by Django 4.1.4 on 2023-02-05 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_content_content_type_alter_content_module_and_more'),
        ('accounts', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Подпись')),
                ('content', django_quill.fields.QuillField(verbose_name='Ответ')),
                ('file', models.FileField(blank=True, help_text='Если требуется, прикрепите файл', upload_to='answer_files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', django_quill.fields.QuillField(blank=True, help_text='Комментарий преподователя', verbose_name='Комментарий')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='Дата проверки')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Оценка за ответ студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.task')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
