# Generated by Django 4.1.4 on 2023-02-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
        ),
    ]
