# Generated by Django 4.1.4 on 2023-02-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentquizresult'),
        ('courses', '0007_alter_content_content_type_quiz_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz', verbose_name='results'),
        ),
        migrations.AddField(
            model_name='studentquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='quiz_results'),
        ),
    ]
