# Generated by Django 4.1.4 on 2023-02-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_answer_correct_alter_answer_question_and_more'),
        ('accounts', '0005_studentquizresult_quiz_studentquizresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='studentquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
