# Generated by Django 4.1.2 on 2022-11-14 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="overview",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                help_text="Адресная строка",
                max_length=200,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.subject",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="images/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="text",
            name="content",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
    ]
