# Generated by Django 4.1.4 on 2023-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_content_content_type_quiz_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number_of_answers',
            field=models.IntegerField(default=5, verbose_name='Количество вариантов ответа'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'легкий'), ('medium', 'средний'), ('hard', 'сложный')], default='medium', max_length=6, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(help_text='Количество отображаемых вопросов у студента (фактически их может быть больше)', verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='В процентах %. На какое минимальное количество процентов вопросов должен ответить студент.', verbose_name='Требуемый результат для прохождения теста'),
        ),
    ]
