# Generated by Django 4.1.4 on 2023-10-19 16:40

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_slug_alter_quiz_number_of_answers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="module_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена модуля",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, help_text="Порядок модулей"),
        ),
    ]
